### ISSUE TITLE
Problem When Adding an Additional Axis

### ISSUE THREAD

**Issue by Cengizhanky** [Levi-Armstrong/tesseract_ros_workcell#15]
I was trying to add a new 8th axis to the rail inside **workcell_rail** example. I believe I already edited all necessary files like this
[workcell_rail_plugins.yaml](https://gist.github.com/Cengizhanky/b97391576d38af09419eded32313fbc3#file-workcell_rail_plugins-yaml-L43-L44) 
[application_rail.launch](https://gist.github.com/Cengizhanky/e6704a195b5b6e655fb5a9fbdd9f8913#file-application_rail-launch-L37) 
[workcell_rail.urdf](https://gist.github.com/Cengizhanky/716875e3cc081def36ec5ef59a8c0d8d#file-workcell_rail-urdf-L369-L422) 
[raster_application.h](https://gist.github.com/Cengizhanky/9174d25e776cec22a72ba2a2a42d38c6#file-raster_application-h-L108)

After doing these changes I did `catkin build`, then I run `roslaunch twc_application application_rail.launch`. Descartes process begins but it fails like [this](https://gist.github.com/Cengizhanky/16b2cf9e7c92b58f2f228eff3028110c#file-error-log-L246-L252)

I don't know if this is a bug or not but any suggestion will be helpfull, Thank You.

**Comment by savolla** [comment]
I mentioned exact same issue [here](https://github.com/tesseract-robotics/tesseract/discussions/750). It was a matrix multiplication error.
